packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  lefthook: true
strictDepBuilds: true
minimumReleaseAge: 1440
trustPolicy: no-downgrade
trustPolicyExclude:
  - "semver"
blockExoticSubdeps: true
minimumReleaseAgeExclude:
  - otsukimi-ui@1.2.1
