apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord
    receivers:
      - uid: discord
        type: discord
        disableResolveMessage: false
        settings:
          url: $GF_DISCORD_WEBHOOK_URL
          use_discord_username: false
