events {}

http {
	upstream frontend {
		server frontend:5173;
	}

	upstream backend {
		server backend:3000;
	}

	access_log off;

	map $http_upgrade $connection_upgrade {
		default upgrade;
		'' close;
	}

	absolute_redirect off;

	server {
		listen 80;

		# Backend
		location /api/ {
			proxy_pass http://backend/;

            proxy_set_header Host $host;
        	proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		}

		location /api {
			return 308 /api/;
		}

		# Frontend
		location / {
            proxy_pass http://frontend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

			# Vite HMR
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
