input {
  gelf {}
}

filter {
  json {
    source => "message"
  }
  mutate {
    rename => { "host" => "[host][name]" }
  }
}

output {
  elasticsearch {
    hosts => "http://elasticsearch:9200"
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
  }
}
